site_name: SAR Doc
site_url: https://gabrielmacedoanac.github.io/sardoc
site_author: ANAC
site_description: Site estático da Superintendência de Aeronavegabilidade (SAR), Agência Nacional de Aviação Civil (ANAC), construído a partir de um conjunto de arquivos em Markdown para hospedar a documentação de interesse da superintendência. Conteúdo personalizável, pesquisável e compatível com dispositivos móveis (responsivo).

# Repository
repo_name: Github
repo_url: https://github.com/gabrielmacedoanac/sardoc
edit_uri: "edit/main/docs/"

theme:
  name: material
  shortcuts:
      help: 191    # ?
#      next: 78     # n
#      previous: 80 # p
      previous: 37 # ArrowLeft
      next: 39 # ArrowRight
#      https://keycode.info/
#      https://www.mkdocs.org/user-guide/styling-your-docs/
      search: 83   # s
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  highlightjs: true
  hljs_languages:
    - yaml
  sticky_navigation: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo        
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue      
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
  language: 'en'
  icon:
    logo: material/book-open-page-variant
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
#    - navigation.sections
# 404 page
  static_templates:
    - 404.html

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg  
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true  
  - pymdownx.magiclink:
      repo_url_shortener: true
      social_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      provider: 'github'
  - pymdownx.mark
  - pymdownx.progressbar
#  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:
  - toc:
      permalink: '✈'
#      permalink: '#'
      
plugins:
  - search:
      lang: en
# Padrão do separador de busca: separator: '[\s\-\.]+' substituído por "\s"
      separator: '[\s]+'
# 3 já é o padrão      min_search_length: 3
  - macros
  - mermaid2:
      arguments:
        securityLevel: 'loose'      
        theme: |
            ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
        
extra:
  disqus: sardoc
  manifest: 'manifest.webmanifest'

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js
